name: balatodo
description: "A Balatro inspired to-do list with sections for organizing tasks by difficulty."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.1.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  # All latest versions as of 4-7-2025
  audioplayers: ^6.0.0 
  shared_preferences: ^2.5.3
  file_picker: ^10.0.0
  path_provider: ^2.1.5
  share_plus: ^10.1.4

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  # Required for custom app icon
  flutter_launcher_icons: ^0.14.3

  flutter_lints: ^5.0.0

# The following section is specific to Flutter packages.
flutter:
  assets:
      # Chip & BG image assets
      - assets/images/
      - assets/images/variants/
      - assets/sounds/
      - assets/icons/
      - assets/music/
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true